print(True and True)
print(True and False)
print(False and True)
print(False and False)

print(True or True)
print(True or False)
print(False or True)
print(False or False)

print(not True)
print(not False)

print(0 and 5)
print("" and 5)
print(None and 5)
print([] and 5)
print(1 and 5)
print(2 and 5)
print("/////////////////")
print(0 or 5)
print("" or 5)
print(None or 5)
print([] or 5)
print(1 or 5)
print(2 or 5)